import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// this would come from the cookie of the user
const name = 'Amazing';

export default function Home() {
	return (
		<div className={styles.page}>
			<Head>
				<title>Beatific Demo</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<section className={styles.login}>
					<div className={styles.mid}>
						<div className={styles.emoji}>
							<Image
								width={68}
								height={68}
								src='/520464@2x.png'
								alt='Smiling face'
								objectFit='cover'
								objectPosition='contain'
							/>
						</div>
						<h1 className={styles.greeting}>Hi {name}</h1>
						<h2 className={styles.formName}>Login</h2>
						<form className={styles.formSection}>
							<input type='email' name='email' id='email' placeholder='email' />
							<input
								type='password'
								name='password'
								id='password'
								placeholder='password'
							/>
							<button type='submit'>
								<Image
									src='/Group_306@2x.png'
									width={39}
									height={11}
									alt='Arrow'
								/>
							</button>
						</form>
						<p className={styles.forgotPass}>FORGOT PASSWORD</p>
					</div>
					<div className={styles.footerLinks}>
						<p>{"DON'T"} HAVE AN ACCOUNT?</p>
						<p>CREATE AN ACCOUNT</p>
						<a href='/create-account'>
							<Image
								src='/Group_291@2x.png'
								height={11}
								width={27}
								alt='Arrow'
							/>
						</a>
					</div>
				</section>
			</main>
		</div>
	);
}
