import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

// this would come from the cookie of the user
const name = 'Amazing';

export default function Home() {
	const [passwordVisible, setPasswordVisible] = useState(false);

	const handleClick = (e) => {
		setPasswordVisible(!passwordVisible);
	};

	return (
		<div className={styles.page}>
			<Head>
				<title>Beatific Demo</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<section className={styles.login}>
					<div className={styles.mid}>
						<div className={styles.emoji}>
							<Image
								width={68}
								height={68}
								src='/520464@2x.png'
								alt='Smiling face'
								objectFit='cover'
								objectPosition='contain'
							/>
						</div>
						<h1 className={styles.greeting}>Hi {name}</h1>
						<h2 className={styles.formName}>Login</h2>
						<form className={styles.formSection}>
							<div className={styles.formInput}>
								<span className={styles.icon}>
									<Image
										src='/482947.svg'
										alt='mail icon'
										height={22}
										width={30}
									/>
								</span>
								<input
									type='email'
									name='email'
									id='email'
									placeholder='email'
									required
								/>
							</div>
							<div className={styles.formInput}>
								<span className={styles.icon}>
									<Image
										src='/2886699.svg'
										alt='lock icon'
										width={30}
										height={22}
									/>
								</span>
								<input
									type={passwordVisible ? 'text' : 'password'}
									name='password'
									id='password'
									placeholder='password'
									required
								/>
								<span className={styles.showPass} onClick={handleClick}>
									<svg
										xmlns='http://www.w3.org/2000/svg'
										className={styles.eye}
										fill='none'
										viewBox='0 0 24 24'
										stroke='currentColor'
										strokeWidth={2}
									>
										<path
											strokeLinecap='round'
											strokeLinejoin='round'
											d='M15 12a3 3 0 11-6 0 3 3 0 016 0z'
										/>
										<path
											strokeLinecap='round'
											strokeLinejoin='round'
											d='M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z'
										/>
									</svg>
								</span>
							</div>
							<button type='submit'>
								<Image
									src='/Group_306@2x.png'
									width={39}
									height={11}
									alt='Arrow'
								/>
							</button>
						</form>
						<p className={styles.forgotPass}>FORGOT PASSWORD</p>
					</div>
					<div className={styles.footerLinks}>
						<p>{"DON'T"} HAVE AN ACCOUNT?</p>
						<p>CREATE AN ACCOUNT</p>
						<a href='/create-account'>
							<Image
								src='/Group_291@2x.png'
								height={11}
								width={27}
								alt='Arrow'
							/>
						</a>
					</div>
				</section>
			</main>
		</div>
	);
}
